name: chromedriver
on: workflow_dispatch
jobs:
  chromdriver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install selenium
        run: pip install selenium
      - name: Test
        run: python chromedriver.py
