name: genderex-test
on: workflow_dispatch
jobs:
  genderex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JRE 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jre
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install GenderEx
        run: pip install spotify-gender-ex
      
      - name: Run GenderEx
        run: spotify-gender-ex --noia --debug
      
      - name: Store logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./GenderEx/output/log/
      
      - name: Upload to Dropbox
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: ./GenderEx/output/*
          dest: /
          multiple: true
