name: MEGA
on: workflow_dispatch
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Get testfile
        run: wget https://speed.hetzner.de/100MB.bin
      
      - name: Upload testfile
        uses: Difegue/action-megacmd@master
        with:
          args: put . /Spotify-GenderEx/
        env:
          USERNAME: ${{ secrets.MEGA_USER }}
          PASSWORD: ${{ secrets.MEGA_PASS }}
