name: PR test
on:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Hello World, this is me ;-)" > HELLO.txt          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hello
          path: HELLO.txt
      
      - name: Fail
        run: |
          echo "${{ github.event_name }}"
          exit 1

      - name: Comment PR
        if: ${{ always() && github.event_name == "pull_request" }}
        run: sleep 60
