name: PR test
on:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Hello World, this is me ;-)" > HELLO.txt          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hello
          path: HELLO.txt

      - name: Comment PR
        if: ${{ always() && github.event_name == 'pull_request' }}
        run: |
          curl -SsL --fail-with-body -w "\n" -X POST https://av.thetadev.de/.well-known/api/prComment -H "Content-Type: application/json" --data "{\"url\": \"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_NUMBER\", \"pr\": ${{ github.event.number }}}"
